### ISSUE TITLE
Gnome Shell 3.18 is coming. Hopes this helps.

### ISSUE THREAD

**Issue by nls1729** [emerinohdz/status-title-bar#29]
I received a bug report on my extension Activities Configurator that was caused by a conflict with Status Title Bar.  You had your way with the Application Menu Button, destroyed it and replaced it. My extension just poked around with the insides of the button.  Well no harm, no foul, I was able to workaround the problem and now the two extensions coexist peacefully on GS 3.16.  

I am in the process of getting ready for GS 3.18.  In 3.17.90 one option in my extension failed. The signal "maximize" is no longer provided by the window manager and  "unmaximize" is no longer provided.  I had a heck of a time finding a workaround for the loss of the signals in activities-config .

I was able to use new signals "hide-title-preview" for "maximize" and  "size-change" for "unmaximize".
 
I made the substitution of the signals in  the Status Title Bar Extension.  I haven't examined your code closely or tested it extensively but that seems to fix it for 3.17.91 .

I hope this information is useful.

Regards,

Norman

**Comment by emerinohdz** [comment]
Hello @nls1729! Thank you very much for sharing this information, I'll be sure to check it as time allows it. Too bad you had problems with the extension, as you say it actually replaces the whole menu button, the new menu button actually "extends" the original one but it does changes it nevertheless. How did you manage to workaround this? It'll be good to know, so that I can refactor the code and don't break other extensions!

**Comment by nls1729** [comment]
Hello:
There is really nothing wrong with the way your extension is designed.  Extending a class and replacing the instance of the original base class is very common practice for gnome shell extensions.  Extensions are actually patches to the shell code which can result in conflicts when different extensions deal with the same original code.  I have been able to handle this and other conflicts by detection and mediation.  My extension detects the conflict and adjusts its behavior to resolve the conflict.  In this case I simply connected to the "actor-added" signal of the left box and when signaled, checked if your extension has replaced the app menu button and if so,  make my changes to the new instance of the button.  All extensions are disabled and re-enabled during shell mode changes such as screen locking.  Most conflicts occur at extension enable or disable time.  I don't think there is any foolproof way to eliminate conflicts before hand. You have to deal with them when they are discovered.
Regards,
Norman

**Comment by emerinohdz** [comment]
That seems correct then, I was just wondering how you solved it. Thanks for
sharing!
