### ISSUE TITLE
title override the clock

### ISSUE THREAD

**Issue by ghost** [emerinohdz/status-title-bar#31]
Hi.
The extension is so useful, but I have issue with its title: it overwrite the clock in gnome-shell 3.10.4 if you go to the webpage like https://www.youtube.com/watch?v=EgT_us6AsDg in google chrome.
Hope u fix it soon

**Comment by emerinohdz** [comment]
Unfortunately, this was an issue with previous version of gnome shell, 
newer gnome shell versions don't have this problem. What distro are you 
using? I'll see if there's something I can do, but AFAIK latest versions 
are not compatible with 3.10. I'll appreciate if you could test latest 
version available on GSE site (or the one available on github, master 
branch) and see if that works for you, if it does, I'll be more than 
glad to provide a workaround for older versions having this issue.
