### ISSUE TITLE
Gnome 3.20 support

### ISSUE THREAD

**Issue by watermelonjuice** [emerinohdz/status-title-bar#32]
This extension does not support 3.20 according to extensions.gnome.org

**Comment by Gedweb** [comment]
+1
Gnome 3.20.2 — window title leave on place.
Title text move to gnome panel.

**Comment by emerinohdz** [comment]
Hello, I'm sorry for the very late response (I don't know why I didn't get notified the first time), lastest version supports gs 3.20, available also at extensions.gnome.org (https://extensions.gnome.org/extension/59/status-title-bar/). Please let me know if you have any problem, feel free to reopen if you do.
