### ISSUE TITLE
Seems like Gnome 3.32 broke this extension again

### ISSUE THREAD

**Issue by elmagio** [emerinohdz/status-title-bar#36]
Just upgraded to Ubuntu 19.04 and it doesn't work.

**Comment by emerinohdz** [comment]
Sorry, just saw this. Could you please provide more details? 
- Gnome Shell version
- Status Title Bar version

Any errors?

**Comment by elmagio** [comment]
Gnome shell is on version 3.32.0 and Status Title Bar was installed from there: [https://extensions.gnome.org/extension/59/status-title-bar/](url). 

And it just says "Error loading extension".

**Comment by emerinohdz** [comment]
Problem fixed. Submitted to GSE, once approved make sure to update and comment the results here so I can close the ticket (or you can try installing manually from source too).

Thanks for reporting!

**Comment by elmagio** [comment]
Seems like it's working again ! Thanks !
